version: '3.8'
services:
    db:
        image: mongo:latest
        container_name: microservice_mongo_db
        restart: always
        ports:
            - 27017:27017
        volumes:
            - microservice:/data/db
        environment:
            - MONGO_INITDB_ROOT_USERNAME=admin
            - MONGO_INITDB_ROOT_PASSWORD=pass123
volumes:
    microservice:
